core-ai-uri: ${SERVICE_SCHEME}://${CORE_AI_HOST}:${CORE_AI_PORT}

server:
  port: ${SERVER_PORT}

spring:
  application:
    name: be-core-messaging-app

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER}/oauth2/jwks
          issuer-uri: ${AUTH_SERVER}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=messaging
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

mail:
  imap:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

#    protocol: imaps
#    props:
#      mail.imap.ssl.enable: true
#      mail.imap.auth: true
#      mail.imap.starttls.enable: true
#      mail.imap.connectiontimeout: 5000
#      mail.imap.timeout: 5000

management:
  tracing:
    enabled : true
    sampling:
      probability: 1.0
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /api/messaging/v3/api-docs
  swagger-ui:
    enabled: true
    csrf:
      enabled: true
    path: /api/messaging/swagger-ui.html