server:
  port: ${SERVER_PORT}

spring:
  application:
    name: be-core-messaging-app
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
mail:
  imap:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    # 需要Google账户生成应用专用密码
#    protocol: imaps
#    props:
#      mail.imap.ssl.enable: true
#      mail.imap.auth: true
#      mail.imap.starttls.enable: true
#      mail.imap.connectiontimeout: 5000
#      mail.imap.timeout: 5000

management:
  tracing:
    enabled : true
    sampling:
      probability: 1.0
  endpoints:
    web:
      base-path: ""
      path-mapping:
        health: health
  health:
    ldap:
      enabled: false